[34m[1mwandb[0m: Downloading large artifact model:v229, 327.43MB. 1 files...
[34m[1mwandb[0m:   1 of 1 files downloaded.
Done. 0:0:0.5
ðŸ“‚ Directory contents: ['model.pth']
ðŸ“Œ Loading model from: /home/edramos/Documents/MLOPS/WBC-Cancer/artifacts/model:v229/model.pth
     [37;48;2;0;113;102m INFO [0m  [1;92m127.0.0.1[0m:[1;36m45140[0m - [32m"POST /predict/deit3_tiny_patch16_224 HTTP/1.1"[0m [1;36m500[0m
    [37;48;2;0;113;102m ERROR [0m  Exception in ASGI application
Traceback (most recent call last):
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edramos/Documents/MLOPS/WBC-Cancer/main.py", line 108, in predict
    model = load_model(wandb_codes[model_name], model_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edramos/Documents/MLOPS/WBC-Cancer/main.py", line 47, in load_model
    model = timm.create_model(model_name, pretrained=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edramos/miniconda3/envs/pytorch/lib/python3.12/site-packages/timm/models/_factory.py", line 122, in create_model
    raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (deit3_tiny_patch16_224)
     [37;48;2;0;113;102m INFO [0m  Shutting down
     [37;48;2;0;113;102m INFO [0m  Waiting for application shutdown.
     [37;48;2;0;113;102m INFO [0m  Application shutdown complete.
     [37;48;2;0;113;102m INFO [0m  Finished server process [1m[[0m[1;36m3914174[0m[1m][0m
